package com.ponpains.shioriarchive;

import android.app.DatePickerDialog;
import android.content.Intent;
import android.graphics.Color;
import android.graphics.Typeface;
import android.graphics.drawable.GradientDrawable;
import android.net.Uri;
import android.os.Bundle;
import android.text.Editable;
import android.text.TextWatcher;
import android.view.Gravity;
import android.view.View;
import android.widget.*;
import androidx.annotation.Nullable;
import androidx.appcompat.app.AppCompatActivity;
import java.time.LocalDate;
import java.time.YearMonth;
import java.time.format.DateTimeFormatter;
import java.util.*;

public class MainActivity extends AppCompatActivity {
    static final int INK=Color.rgb(32,33,36), PAPER=Color.rgb(250,249,246), ACCENT=Color.rgb(66,92,89), ACCENT_DARK=Color.rgb(42,61,59), SOFT=Color.rgb(225,233,231), LINE=Color.rgb(226,225,220), MUTED=Color.rgb(105,105,105);
    ArchiveRepository repo; List<ArchiveEvent> events=new ArrayList<>(); String updated=""; FrameLayout content; TextView status;
    LocalDate selectedDate=LocalDate.now(); YearMonth shownMonth=YearMonth.from(LocalDate.now());
    Spinner yearSpinner, monthSpinner; GridLayout monthGrid; TextView monthStats, dayHeader; LinearLayout dayOut; boolean spinnerLock=false;

    @Override protected void onCreate(@Nullable Bundle b){super.onCreate(b);repo=new ArchiveRepository(this);ArchiveRepository.ArchiveData d=repo.loadBestAvailable();events=d.events;updated=d.updatedAt;setContentView(shell());home();repo.refreshIfNeeded((e,u)->{events=e;updated=u;status.setText(stat());home();});}

    View shell(){LinearLayout r=col();r.setPadding(dp(18),dp(14),dp(18),dp(10));r.addView(tx("詩央里暦",28,INK,true));r.addView(tx("永田詩央里さんの記録を、1日ずつたどる",13,MUTED,false));status=tx(stat(),11,MUTED,false);status.setPadding(0,dp(3),0,dp(10));r.addView(status);content=new FrameLayout(this);r.addView(content,new LinearLayout.LayoutParams(-1,0,1));LinearLayout nav=new LinearLayout(this);nav.setOrientation(LinearLayout.HORIZONTAL);nav.setGravity(Gravity.CENTER);nav.addView(nb("今日",v->home()),nlp());nav.addView(nb("カレンダー",v->calendar()),nlp());nav.addView(nb("日誌",v->diary()),nlp());nav.addView(nb("検索",v->search()),nlp());r.addView(nav);return r;}
    String stat(){return "確認済み "+events.size()+"件  ·  記録のある日 "+activeDays()+"日  ·  更新 "+(updated.isEmpty()?"—":updated);} int activeDays(){Set<LocalDate>s=new HashSet<>();for(ArchiveEvent e:events)s.add(e.date);return s.size();}
    LinearLayout.LayoutParams nlp(){LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(0,dp(46),1);p.setMargins(dp(2),0,dp(2),0);return p;} Button nb(String s,View.OnClickListener l){Button b=new Button(this);b.setText(s);b.setAllCaps(false);b.setTextSize(12);b.setTextColor(INK);b.setBackground(bg(Color.WHITE,16,LINE));b.setOnClickListener(l);return b;}

    void home(){LinearLayout b=col();LocalDate now=LocalDate.now();b.addView(tx(now.getMonthValue()+"月"+now.getDayOfMonth()+"日",31,INK,true));b.addView(tx("歴代の今日",14,ACCENT,true));int n=0;for(ArchiveEvent e:events)if(e.date.getMonthValue()==now.getMonthValue()&&e.date.getDayOfMonth()==now.getDayOfMonth()){b.addView(card(e));n++;}if(n==0)b.addView(empty("この日付の記録は、まだ登録されていません。"));TextView h=tx("最近の記録",19,INK,true);h.setPadding(0,dp(24),0,0);b.addView(h);for(int i=0;i<Math.min(12,events.size());i++)b.addView(card(events.get(i)));screen(scroll(b));}

    void calendar(){LinearLayout b=col();b.addView(tx("カレンダー",27,INK,true));b.addView(tx("色付きの日には記録があります。数字の下はその日の件数です。",13,MUTED,false));
        LinearLayout controls=new LinearLayout(this);controls.setOrientation(LinearLayout.HORIZONTAL);controls.setGravity(Gravity.CENTER_VERTICAL);controls.setPadding(0,dp(10),0,dp(6));
        Button prev=nb("‹",v->{shownMonth=shownMonth.minusMonths(1);syncSpinners();renderCalendar();});Button next=nb("›",v->{shownMonth=shownMonth.plusMonths(1);syncSpinners();renderCalendar();});
        controls.addView(prev,new LinearLayout.LayoutParams(dp(46),dp(46)));
        yearSpinner=new Spinner(this);monthSpinner=new Spinner(this);
        List<String> years=new ArrayList<>();int min=Math.min(2019,minYear()),max=Math.max(LocalDate.now().getYear(),maxYear());for(int y=min;y<=max;y++)years.add(y+"年");
        yearSpinner.setAdapter(new ArrayAdapter<>(this,android.R.layout.simple_spinner_dropdown_item,years));List<String> months=new ArrayList<>();for(int m=1;m<=12;m++)months.add(m+"月");monthSpinner.setAdapter(new ArrayAdapter<>(this,android.R.layout.simple_spinner_dropdown_item,months));
        controls.addView(yearSpinner,new LinearLayout.LayoutParams(0,dp(48),1));controls.addView(monthSpinner,new LinearLayout.LayoutParams(0,dp(48),1));controls.addView(next,new LinearLayout.LayoutParams(dp(46),dp(46)));b.addView(controls);
        yearSpinner.setOnItemSelectedListener(new AdapterView.OnItemSelectedListener(){public void onNothingSelected(AdapterView<?>p){}public void onItemSelected(AdapterView<?>p,View v,int pos,long id){if(spinnerLock)return;int y=Integer.parseInt(years.get(pos).replace("年",""));shownMonth=YearMonth.of(y,shownMonth.getMonthValue());renderCalendar();}});
        monthSpinner.setOnItemSelectedListener(new AdapterView.OnItemSelectedListener(){public void onNothingSelected(AdapterView<?>p){}public void onItemSelected(AdapterView<?>p,View v,int pos,long id){if(spinnerLock)return;shownMonth=YearMonth.of(shownMonth.getYear(),pos+1);renderCalendar();}});
        monthStats=tx("",12,MUTED,false);b.addView(monthStats);monthGrid=new GridLayout(this);monthGrid.setColumnCount(7);monthGrid.setUseDefaultMargins(false);b.addView(monthGrid,new LinearLayout.LayoutParams(-1,-2));
        dayHeader=tx("",20,INK,true);dayHeader.setPadding(0,dp(18),0,dp(2));b.addView(dayHeader);dayOut=col();b.addView(dayOut);syncSpinners();renderCalendar();renderDay(selectedDate,dayHeader,dayOut);screen(scroll(b));}

    int minYear(){int y=LocalDate.now().getYear();for(ArchiveEvent e:events)y=Math.min(y,e.date.getYear());return y;}int maxYear(){int y=LocalDate.now().getYear();for(ArchiveEvent e:events)y=Math.max(y,e.date.getYear());return y;}
    void syncSpinners(){if(yearSpinner==null)return;spinnerLock=true;int min=Math.min(2019,minYear());yearSpinner.setSelection(Math.max(0,shownMonth.getYear()-min),false);monthSpinner.setSelection(shownMonth.getMonthValue()-1,false);spinnerLock=false;}
    void renderCalendar(){if(monthGrid==null)return;monthGrid.removeAllViews();String[] w={"月","火","水","木","金","土","日"};for(String s:w){TextView v=tx(s,11,MUTED,true);v.setGravity(Gravity.CENTER);monthGrid.addView(v,gp(dp(30)));}
        Map<LocalDate,Integer> counts=new HashMap<>();int total=0;for(ArchiveEvent e:events)if(YearMonth.from(e.date).equals(shownMonth)){counts.put(e.date,counts.getOrDefault(e.date,0)+1);total++;}
        int blanks=shownMonth.atDay(1).getDayOfWeek().getValue()-1;for(int i=0;i<blanks;i++){TextView z=tx("",12,MUTED,false);monthGrid.addView(z,gp(dp(58)));}
        for(int d=1;d<=shownMonth.lengthOfMonth();d++){LocalDate date=shownMonth.atDay(d);int n=counts.getOrDefault(date,0);TextView v=tx(n>0?d+"\n"+n+"件":String.valueOf(d),n>0?13:13,n>0?Color.WHITE:INK,n>0);v.setGravity(Gravity.CENTER);boolean sel=date.equals(selectedDate);v.setBackground(bg(sel?ACCENT_DARK:(n>0?ACCENT:Color.WHITE),12,sel?INK:(n>0?ACCENT:LINE)));v.setOnClickListener(x->{selectedDate=date;renderCalendar();renderDay(date,dayHeader,dayOut);});monthGrid.addView(v,gp(dp(58)));}
        monthStats.setText(shownMonth.getYear()+"年"+shownMonth.getMonthValue()+"月  ·  "+total+"件  ·  記録のある日 "+counts.size()+"日");}
    GridLayout.LayoutParams gp(int h){GridLayout.LayoutParams p=new GridLayout.LayoutParams();p.width=0;p.height=h;p.columnSpec=GridLayout.spec(GridLayout.UNDEFINED,1f);p.setMargins(dp(2),dp(2),dp(2),dp(2));return p;}

    void diary(){LinearLayout b=col();b.addView(tx("1日の日誌",27,INK,true));b.addView(tx("その日に確認できた記録を、時刻順にまとめて表示します。",13,MUTED,false));LinearLayout controls=new LinearLayout(this);controls.setOrientation(LinearLayout.HORIZONTAL);controls.setPadding(0,dp(10),0,dp(4));Button prev=nb("前の日",v->{selectedDate=selectedDate.minusDays(1);diary();});Button pick=nb("日付を選ぶ",v->pickDate());Button next=nb("次の日",v->{selectedDate=selectedDate.plusDays(1);diary();});controls.addView(prev,new LinearLayout.LayoutParams(0,dp(46),1));controls.addView(pick,new LinearLayout.LayoutParams(0,dp(46),1));controls.addView(next,new LinearLayout.LayoutParams(0,dp(46),1));b.addView(controls);TextView h=tx("",21,INK,true);b.addView(h);LinearLayout out=col();b.addView(out);renderDay(selectedDate,h,out);screen(scroll(b));}
    void pickDate(){DatePickerDialog d=new DatePickerDialog(this,(v,y,m,day)->{selectedDate=LocalDate.of(y,m+1,day);shownMonth=YearMonth.from(selectedDate);diary();},selectedDate.getYear(),selectedDate.getMonthValue()-1,selectedDate.getDayOfMonth());d.show();}
    void renderDay(LocalDate d,TextView h,LinearLayout out){List<ArchiveEvent> list=new ArrayList<>();for(ArchiveEvent e:events)if(e.date.equals(d))list.add(e);list.sort((a,b)->timeKey(a.time).compareTo(timeKey(b.time)));h.setText(d.format(DateTimeFormatter.ofPattern("yyyy年M月d日"))+"  ·  "+list.size()+"件");out.removeAllViews();if(list.isEmpty()){out.addView(empty("この日の確認済み記録はありません。"));return;}Map<String,Integer> types=new LinkedHashMap<>();for(ArchiveEvent e:list)types.put(e.type,types.getOrDefault(e.type,0)+1);TextView meta=tx(joinTypes(types),12,ACCENT,false);meta.setPadding(0,dp(4),0,dp(3));out.addView(meta);for(ArchiveEvent e:list)out.addView(diaryCard(e));}
    String timeKey(String s){return s==null||s.isEmpty()?"99:99:99":s;}String joinTypes(Map<String,Integer> m){List<String>a=new ArrayList<>();for(Map.Entry<String,Integer>e:m.entrySet())a.add(e.getKey()+" "+e.getValue());return String.join("  ·  ",a);}

    void search(){LinearLayout b=col();b.addView(tx("検索",27,INK,true));b.addView(tx("出来事・媒体・人物・タグを横断します。",13,MUTED,false));EditText q=new EditText(this);q.setHint("例：ラジオ / 喫茶店 / 鈴木瞳美 / 2025");q.setSingleLine();q.setBackground(bg(Color.WHITE,16,LINE));q.setPadding(dp(14),0,dp(14),0);LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,dp(52));p.setMargins(0,dp(12),0,dp(8));b.addView(q,p);TextView count=tx("",12,MUTED,false);b.addView(count);LinearLayout out=col();b.addView(out);results("",out,count);q.addTextChangedListener(new TextWatcher(){public void beforeTextChanged(CharSequence s,int a,int c,int d){}public void onTextChanged(CharSequence s,int a,int c,int d){results(s.toString(),out,count);}public void afterTextChanged(Editable e){}});screen(scroll(b));}
    void results(String q,LinearLayout out,TextView count){out.removeAllViews();int n=0;for(ArchiveEvent e:events)if(e.matches(q)){if(q.trim().isEmpty()&&n>=15)break;out.addView(card(e));n++;}count.setText(q.trim().isEmpty()?"新しい順に15件":n+"件見つかりました");if(n==0)out.addView(empty("該当する記録はありません。"));}

    View diaryCard(ArchiveEvent e){LinearLayout row=new LinearLayout(this);row.setOrientation(LinearLayout.HORIZONTAL);row.setGravity(Gravity.TOP);LinearLayout.LayoutParams rp=new LinearLayout.LayoutParams(-1,-2);rp.setMargins(0,dp(8),0,0);row.setLayoutParams(rp);TextView time=tx(e.time.isEmpty()?"時刻\n不明":e.time,12,e.time.isEmpty()?MUTED:ACCENT,true);time.setGravity(Gravity.CENTER);time.setPadding(0,dp(12),dp(8),0);row.addView(time,new LinearLayout.LayoutParams(dp(62),-2));View c=compactCard(e);row.addView(c,new LinearLayout.LayoutParams(0,-2,1));return row;}
    View compactCard(ArchiveEvent e){LinearLayout c=col();c.setPadding(dp(14),dp(12),dp(14),dp(12));c.setBackground(bg(Color.WHITE,16,LINE));TextView pill=tx(e.type,11,ACCENT,true);c.addView(pill);TextView t=tx(e.title,16,INK,true);t.setPadding(0,dp(5),0,dp(2));c.addView(t);if(!e.summary.isEmpty())c.addView(tx(e.summary,13,INK,false));if(!e.tags.isEmpty()){TextView z=tx("#"+String.join("  #",e.tags),11,ACCENT,false);z.setPadding(0,dp(6),0,0);c.addView(z);}TextView s=tx("出典："+e.sourceName,10,MUTED,false);s.setPadding(0,dp(7),0,0);c.addView(s);if(e.sourceUrl.startsWith("http")){Button o=nb("出典",v->open(e.sourceUrl));LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(dp(80),dp(38));p.gravity=Gravity.END;p.setMargins(0,dp(5),0,0);c.addView(o,p);}return c;}
    View card(ArchiveEvent e){LinearLayout c=col();c.setPadding(dp(15),dp(14),dp(15),dp(14));c.setBackground(bg(Color.WHITE,18,LINE));LinearLayout.LayoutParams cp=new LinearLayout.LayoutParams(-1,-2);cp.setMargins(0,dp(9),0,0);c.setLayoutParams(cp);LinearLayout m=new LinearLayout(this);m.setGravity(Gravity.CENTER_VERTICAL);TextView pill=tx(e.type,11,ACCENT,true);pill.setPadding(dp(8),dp(4),dp(8),dp(4));pill.setBackground(bg(SOFT,20,SOFT));m.addView(pill);m.addView(tx("  "+e.date+(e.time.isEmpty()?"":"  "+e.time),12,MUTED,false));c.addView(m);TextView t=tx(e.title,17,INK,true);t.setPadding(0,dp(9),0,dp(3));c.addView(t);if(!e.summary.isEmpty())c.addView(tx(e.summary,14,INK,false));if(!e.tags.isEmpty()){TextView z=tx("#"+String.join("  #",e.tags),12,ACCENT,false);z.setPadding(0,dp(8),0,0);c.addView(z);}TextView s=tx("出典："+e.sourceName+"  ·  "+e.confidence,11,MUTED,false);s.setPadding(0,dp(9),0,0);c.addView(s);if(e.sourceUrl.startsWith("http")){Button o=nb("出典ページを開く",v->open(e.sourceUrl));LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-2,dp(42));p.gravity=Gravity.END;p.setMargins(0,dp(7),0,0);c.addView(o,p);}return c;}
    View empty(String s){TextView v=tx(s,13,MUTED,false);v.setPadding(dp(15),dp(15),dp(15),dp(15));v.setBackground(bg(Color.WHITE,18,LINE));LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.setMargins(0,dp(10),0,dp(8));v.setLayoutParams(p);return v;}
    void open(String u){try{Uri x=Uri.parse(u);if(!"https".equalsIgnoreCase(x.getScheme())&&!"http".equalsIgnoreCase(x.getScheme()))return;startActivity(new Intent(Intent.ACTION_VIEW,x));}catch(Exception ignored){Toast.makeText(this,"ページを開けませんでした",Toast.LENGTH_SHORT).show();}}
    LinearLayout col(){LinearLayout l=new LinearLayout(this);l.setOrientation(LinearLayout.VERTICAL);l.setBackgroundColor(PAPER);return l;} ScrollView scroll(View v){ScrollView s=new ScrollView(this);s.setFillViewport(true);s.addView(v,new ScrollView.LayoutParams(-1,-2));return s;} void screen(View v){content.removeAllViews();content.addView(v,new FrameLayout.LayoutParams(-1,-1));} TextView tx(String s,int z,int c,boolean b){TextView v=new TextView(this);v.setText(s);v.setTextSize(z);v.setTextColor(c);if(b)v.setTypeface(Typeface.DEFAULT,Typeface.BOLD);return v;} GradientDrawable bg(int f,int r,int st){GradientDrawable d=new GradientDrawable();d.setColor(f);d.setCornerRadius(dp(r));d.setStroke(dp(1),st);return d;} int dp(int v){return Math.round(v*getResources().getDisplayMetrics().density);}
}
