package com.ponpains.shioriarchive;

import android.app.DatePickerDialog;
import android.content.Intent;
import android.graphics.Color;
import android.graphics.Typeface;
import android.graphics.drawable.GradientDrawable;
import android.net.Uri;
import android.os.Bundle;
import android.text.Editable;
import android.text.TextUtils;
import android.text.TextWatcher;
import android.view.Gravity;
import android.view.MotionEvent;
import android.view.View;
import android.widget.*;
import androidx.annotation.Nullable;
import androidx.appcompat.app.AppCompatActivity;
import java.time.LocalDate;
import java.time.YearMonth;
import java.time.format.DateTimeFormatter;
import java.util.*;

public class MainActivity extends AppCompatActivity {
    static final int INK=Color.rgb(32,33,36), PAPER=Color.rgb(242,243,246), ACCENT=Color.rgb(66,133,244), ACCENT_DARK=Color.rgb(37,99,235), SOFT=Color.rgb(227,237,255), LINE=Color.rgb(226,228,232), MUTED=Color.rgb(103,107,115), TEAL=Color.rgb(79,169,159), CELL=Color.WHITE;
    static final int PAGE_HOME=0, PAGE_CALENDAR=1, PAGE_DIARY=2, PAGE_SEARCH=3;
    ArchiveRepository repo; List<ArchiveEvent> events=new ArrayList<>(); String updated=""; FrameLayout content; TextView status;
    LocalDate selectedDate=LocalDate.now(); YearMonth shownMonth=YearMonth.from(LocalDate.now());
    Spinner yearSpinner, monthSpinner; GridLayout monthGrid; TextView monthStats, dayHeader; LinearLayout dayOut; boolean spinnerLock=false;
    int currentPage=PAGE_HOME; float swipeDownX,swipeDownY;

    @Override protected void onCreate(@Nullable Bundle b){super.onCreate(b);repo=new ArchiveRepository(this);ArchiveRepository.ArchiveData d=repo.loadBestAvailable();events=d.events;updated=d.updatedAt;setContentView(shell());goToday();repo.refreshIfNeeded((e,u)->{events=e;updated=u;status.setText(stat());refreshCurrentPage();});}

    @Override public boolean dispatchTouchEvent(MotionEvent ev){
        if(ev.getActionMasked()==MotionEvent.ACTION_DOWN){swipeDownX=ev.getX();swipeDownY=ev.getY();}
        else if(ev.getActionMasked()==MotionEvent.ACTION_UP && currentPage!=PAGE_SEARCH){
            float dx=ev.getX()-swipeDownX,dy=ev.getY()-swipeDownY;
            if(Math.abs(dx)>dp(72)&&Math.abs(dx)>Math.abs(dy)*1.35f){shiftDate(dx<0?1:-1);return true;}
        }
        return super.dispatchTouchEvent(ev);
    }

    View shell(){LinearLayout r=col();r.setPadding(dp(12),dp(12),dp(12),dp(8));r.addView(tx("詩央里暦",27,INK,true));r.addView(tx("永田詩央里さんの記録を、1日ずつたどる",13,MUTED,false));status=tx(stat(),11,MUTED,false);status.setPadding(0,dp(3),0,dp(8));r.addView(status);content=new FrameLayout(this);r.addView(content,new LinearLayout.LayoutParams(-1,0,1));LinearLayout nav=new LinearLayout(this);nav.setOrientation(LinearLayout.HORIZONTAL);nav.setGravity(Gravity.CENTER);nav.addView(nb("今日",v->goToday()),nlp());nav.addView(nb("カレンダー",v->calendar()),nlp());nav.addView(nb("日誌",v->diary()),nlp());nav.addView(nb("検索",v->search()),nlp());r.addView(nav);return r;}
    String stat(){return "確認済み "+events.size()+"件  ·  記録のある日 "+activeDays()+"日  ·  更新 "+(updated.isEmpty()?"—":updated);} int activeDays(){Set<LocalDate>s=new HashSet<>();for(ArchiveEvent e:events)s.add(e.date);return s.size();}
    LinearLayout.LayoutParams nlp(){LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(0,dp(46),1);p.setMargins(dp(2),0,dp(2),0);return p;} Button nb(String s,View.OnClickListener l){Button b=new Button(this);b.setText(s);b.setAllCaps(false);b.setTextSize(12);b.setTextColor(INK);b.setBackground(bg(Color.WHITE,14,LINE));b.setOnClickListener(l);return b;}

    void goToday(){selectedDate=LocalDate.now();shownMonth=YearMonth.from(selectedDate);home();}
    void refreshCurrentPage(){if(currentPage==PAGE_CALENDAR)calendar();else if(currentPage==PAGE_DIARY)diary();else if(currentPage==PAGE_SEARCH)search();else home();}
    void shiftDate(int n){selectedDate=selectedDate.plusDays(n);shownMonth=YearMonth.from(selectedDate);if(currentPage==PAGE_CALENDAR)calendar();else if(currentPage==PAGE_DIARY)diary();else home();}
    String dateTitle(LocalDate d){return d.format(DateTimeFormatter.ofPattern("M月d日（E）",Locale.JAPANESE));}

    void home(){currentPage=PAGE_HOME;LinearLayout b=col();b.addView(tx(dateTitle(selectedDate),31,INK,true));b.addView(tx("左右にフリックすると前日／翌日に移動します",12,MUTED,false));TextView sub=tx("この日の記録",14,ACCENT,true);sub.setPadding(0,dp(9),0,0);b.addView(sub);int n=0;for(ArchiveEvent e:events)if(e.date.equals(selectedDate)){b.addView(card(e));n++;}if(n==0)b.addView(empty("この日の確認済み記録はありません。"));TextView h=tx("近い日の記録",19,INK,true);h.setPadding(0,dp(22),0,0);b.addView(h);List<ArchiveEvent> nearby=new ArrayList<>();for(ArchiveEvent e:events)if(!e.date.equals(selectedDate))nearby.add(e);nearby.sort(Comparator.comparingLong(e->Math.abs(e.date.toEpochDay()-selectedDate.toEpochDay())));for(int i=0;i<Math.min(10,nearby.size());i++)b.addView(card(nearby.get(i)));screen(scroll(b));}

    void calendar(){currentPage=PAGE_CALENDAR;LinearLayout b=col();LinearLayout controls=new LinearLayout(this);controls.setOrientation(LinearLayout.HORIZONTAL);controls.setGravity(Gravity.CENTER_VERTICAL);controls.setPadding(0,dp(2),0,dp(4));Button prev=nb("‹",v->{shownMonth=shownMonth.minusMonths(1);syncSpinners();renderCalendar();});Button next=nb("›",v->{shownMonth=shownMonth.plusMonths(1);syncSpinners();renderCalendar();});controls.addView(prev,new LinearLayout.LayoutParams(dp(42),dp(44)));yearSpinner=new Spinner(this);monthSpinner=new Spinner(this);List<String> years=new ArrayList<>();int min=Math.min(2019,minYear()),max=Math.max(LocalDate.now().getYear(),maxYear());for(int y=min;y<=max;y++)years.add(y+"年");yearSpinner.setAdapter(new ArrayAdapter<>(this,android.R.layout.simple_spinner_dropdown_item,years));List<String> months=new ArrayList<>();for(int m=1;m<=12;m++)months.add(m+"月");monthSpinner.setAdapter(new ArrayAdapter<>(this,android.R.layout.simple_spinner_dropdown_item,months));controls.addView(yearSpinner,new LinearLayout.LayoutParams(0,dp(48),1));controls.addView(monthSpinner,new LinearLayout.LayoutParams(0,dp(48),1));controls.addView(next,new LinearLayout.LayoutParams(dp(42),dp(44)));b.addView(controls);
        yearSpinner.setOnItemSelectedListener(new AdapterView.OnItemSelectedListener(){public void onNothingSelected(AdapterView<?>p){}public void onItemSelected(AdapterView<?>p,View v,int pos,long id){if(spinnerLock)return;int y=Integer.parseInt(years.get(pos).replace("年",""));shownMonth=YearMonth.of(y,shownMonth.getMonthValue());renderCalendar();}});monthSpinner.setOnItemSelectedListener(new AdapterView.OnItemSelectedListener(){public void onNothingSelected(AdapterView<?>p){}public void onItemSelected(AdapterView<?>p,View v,int pos,long id){if(spinnerLock)return;shownMonth=YearMonth.of(shownMonth.getYear(),pos+1);renderCalendar();}});
        monthStats=tx("",11,MUTED,false);monthStats.setPadding(dp(3),0,0,dp(5));b.addView(monthStats);monthGrid=new GridLayout(this);monthGrid.setColumnCount(7);monthGrid.setUseDefaultMargins(false);b.addView(monthGrid,new LinearLayout.LayoutParams(-1,-2));TextView hint=tx("左右フリック：前日／翌日　・　日付タップ：その日を選択",11,MUTED,false);hint.setPadding(dp(3),dp(7),0,0);b.addView(hint);dayHeader=tx("",20,INK,true);dayHeader.setPadding(dp(3),dp(14),0,dp(2));b.addView(dayHeader);dayOut=col();b.addView(dayOut);syncSpinners();renderCalendar();renderDay(selectedDate,dayHeader,dayOut);screen(scroll(b));}

    int minYear(){int y=LocalDate.now().getYear();for(ArchiveEvent e:events)y=Math.min(y,e.date.getYear());return y;}int maxYear(){int y=LocalDate.now().getYear();for(ArchiveEvent e:events)y=Math.max(y,e.date.getYear());return y;}
    void syncSpinners(){if(yearSpinner==null)return;spinnerLock=true;int min=Math.min(2019,minYear());yearSpinner.setSelection(Math.max(0,shownMonth.getYear()-min),false);monthSpinner.setSelection(shownMonth.getMonthValue()-1,false);spinnerLock=false;}
    void renderCalendar(){if(monthGrid==null)return;monthGrid.removeAllViews();String[] w={"日","月","火","水","木","金","土"};for(int i=0;i<7;i++){int c=i==0?Color.rgb(214,75,75):(i==6?ACCENT:INK);TextView v=tx(w[i],11,c,true);v.setGravity(Gravity.CENTER);monthGrid.addView(v,gp(dp(27)));}
        Map<LocalDate,List<ArchiveEvent>> byDay=new HashMap<>();int total=0;Set<LocalDate> active=new HashSet<>();for(ArchiveEvent e:events){byDay.computeIfAbsent(e.date,k->new ArrayList<>()).add(e);if(YearMonth.from(e.date).equals(shownMonth)){total++;active.add(e.date);}}
        int offset=shownMonth.atDay(1).getDayOfWeek().getValue()%7;LocalDate start=shownMonth.atDay(1).minusDays(offset);for(int i=0;i<42;i++){LocalDate date=start.plusDays(i);List<ArchiveEvent> list=byDay.getOrDefault(date,Collections.emptyList());monthGrid.addView(calendarCell(date,YearMonth.from(date).equals(shownMonth),list),gp(dp(86)));}
        monthStats.setText(shownMonth.getYear()+"年"+shownMonth.getMonthValue()+"月  ·  "+total+"件  ·  記録のある日 "+active.size()+"日");}
    View calendarCell(LocalDate date,boolean inMonth,List<ArchiveEvent> list){LinearLayout c=new LinearLayout(this);c.setOrientation(LinearLayout.VERTICAL);c.setPadding(dp(4),dp(4),dp(4),dp(3));c.setGravity(Gravity.TOP);boolean sel=date.equals(selectedDate);c.setBackground(bg(sel?Color.rgb(238,244,255):CELL,9,sel?ACCENT:LINE));TextView day=tx(String.valueOf(date.getDayOfMonth()),12,inMonth?INK:MUTED,true);day.setGravity(Gravity.CENTER);if(sel){day.setTextColor(Color.WHITE);day.setBackground(bg(ACCENT,20,ACCENT));c.addView(day,new LinearLayout.LayoutParams(dp(28),dp(25)));}else c.addView(day,new LinearLayout.LayoutParams(-2,dp(25)));int shown=0;for(ArchiveEvent e:list){if(shown>=2)break;TextView chip=tx(calendarLabel(e),9,Color.WHITE,false);chip.setSingleLine(true);chip.setEllipsize(TextUtils.TruncateAt.END);chip.setGravity(Gravity.CENTER_VERTICAL);chip.setPadding(dp(4),0,dp(4),0);int cc="X".equalsIgnoreCase(e.type)?ACCENT:TEAL;chip.setBackground(bg(cc,5,cc));LinearLayout.LayoutParams cp=new LinearLayout.LayoutParams(-1,dp(20));cp.setMargins(0,dp(2),0,0);c.addView(chip,cp);shown++;}if(list.size()>shown){TextView more=tx("+"+(list.size()-shown),9,MUTED,true);more.setGravity(Gravity.END);c.addView(more,new LinearLayout.LayoutParams(-1,dp(17)));}c.setOnClickListener(v->{selectedDate=date;shownMonth=YearMonth.from(date);syncSpinners();renderCalendar();renderDay(date,dayHeader,dayOut);});return c;}
    String calendarLabel(ArchiveEvent e){String s=e.title==null?"":e.title.trim();if(s.isEmpty()||s.equals("X投稿")||s.equals("本人X投稿"))s=e.type;if(s.length()>18)s=s.substring(0,18);return s;}
    GridLayout.LayoutParams gp(int h){GridLayout.LayoutParams p=new GridLayout.LayoutParams();p.width=0;p.height=h;p.columnSpec=GridLayout.spec(GridLayout.UNDEFINED,1f);p.setMargins(dp(2),dp(2),dp(2),dp(2));return p;}

    void diary(){currentPage=PAGE_DIARY;LinearLayout b=col();b.addView(tx("1日の日誌",27,INK,true));b.addView(tx("左右にフリックすると前日／翌日に移動します",12,MUTED,false));LinearLayout controls=new LinearLayout(this);controls.setOrientation(LinearLayout.HORIZONTAL);controls.setPadding(0,dp(10),0,dp(4));Button prev=nb("前の日",v->{selectedDate=selectedDate.minusDays(1);shownMonth=YearMonth.from(selectedDate);diary();});Button pick=nb("日付を選ぶ",v->pickDate());Button next=nb("次の日",v->{selectedDate=selectedDate.plusDays(1);shownMonth=YearMonth.from(selectedDate);diary();});controls.addView(prev,new LinearLayout.LayoutParams(0,dp(46),1));controls.addView(pick,new LinearLayout.LayoutParams(0,dp(46),1));controls.addView(next,new LinearLayout.LayoutParams(0,dp(46),1));b.addView(controls);TextView h=tx("",21,INK,true);b.addView(h);LinearLayout out=col();b.addView(out);renderDay(selectedDate,h,out);screen(scroll(b));}
    void pickDate(){DatePickerDialog d=new DatePickerDialog(this,(v,y,m,day)->{selectedDate=LocalDate.of(y,m+1,day);shownMonth=YearMonth.from(selectedDate);diary();},selectedDate.getYear(),selectedDate.getMonthValue()-1,selectedDate.getDayOfMonth());d.show();}
    void renderDay(LocalDate d,TextView h,LinearLayout out){List<ArchiveEvent> list=new ArrayList<>();for(ArchiveEvent e:events)if(e.date.equals(d))list.add(e);list.sort((a,b)->timeKey(a.time).compareTo(timeKey(b.time)));h.setText(d.format(DateTimeFormatter.ofPattern("yyyy年M月d日（E）",Locale.JAPANESE))+"  ·  "+list.size()+"件");out.removeAllViews();if(list.isEmpty()){out.addView(empty("この日の確認済み記録はありません。"));return;}Map<String,Integer> types=new LinkedHashMap<>();for(ArchiveEvent e:list)types.put(e.type,types.getOrDefault(e.type,0)+1);TextView meta=tx(joinTypes(types),12,ACCENT,false);meta.setPadding(0,dp(4),0,dp(3));out.addView(meta);for(ArchiveEvent e:list)out.addView(diaryCard(e));}
    String timeKey(String s){return s==null||s.isEmpty()?"99:99:99":s;}String joinTypes(Map<String,Integer> m){List<String>a=new ArrayList<>();for(Map.Entry<String,Integer>e:m.entrySet())a.add(e.getKey()+" "+e.getValue());return String.join("  ·  ",a);}

    void search(){currentPage=PAGE_SEARCH;LinearLayout b=col();b.addView(tx("検索",27,INK,true));b.addView(tx("出来事・媒体・人物・タグを横断します。",13,MUTED,false));EditText q=new EditText(this);q.setHint("例：ラジオ / 喫茶店 / 鈴木瞳美 / 2025 / X");q.setSingleLine();q.setBackground(bg(Color.WHITE,16,LINE));q.setPadding(dp(14),0,dp(14),0);LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,dp(52));p.setMargins(0,dp(12),0,dp(8));b.addView(q,p);TextView count=tx("",12,MUTED,false);b.addView(count);LinearLayout out=col();b.addView(out);results("",out,count);q.addTextChangedListener(new TextWatcher(){public void beforeTextChanged(CharSequence s,int a,int c,int d){}public void onTextChanged(CharSequence s,int a,int c,int d){results(s.toString(),out,count);}public void afterTextChanged(Editable e){}});screen(scroll(b));}
    void results(String q,LinearLayout out,TextView count){out.removeAllViews();int n=0;for(ArchiveEvent e:events)if(e.matches(q)){if(q.trim().isEmpty()&&n>=20)break;out.addView(card(e));n++;}count.setText(q.trim().isEmpty()?"新しい順に20件":n+"件見つかりました");if(n==0)out.addView(empty("該当する記録はありません。"));}

    View diaryCard(ArchiveEvent e){LinearLayout row=new LinearLayout(this);row.setOrientation(LinearLayout.HORIZONTAL);row.setGravity(Gravity.TOP);LinearLayout.LayoutParams rp=new LinearLayout.LayoutParams(-1,-2);rp.setMargins(0,dp(8),0,0);row.setLayoutParams(rp);TextView time=tx(e.time.isEmpty()?"時刻\n不明":e.time,12,e.time.isEmpty()?MUTED:ACCENT,true);time.setGravity(Gravity.CENTER);time.setPadding(0,dp(12),dp(8),0);row.addView(time,new LinearLayout.LayoutParams(dp(62),-2));View c=compactCard(e);row.addView(c,new LinearLayout.LayoutParams(0,-2,1));return row;}
    View compactCard(ArchiveEvent e){LinearLayout c=col();c.setPadding(dp(14),dp(12),dp(14),dp(12));c.setBackground(bg(Color.WHITE,16,LINE));TextView pill=tx(e.type,11,ACCENT,true);c.addView(pill);TextView t=tx(e.title,16,INK,true);t.setPadding(0,dp(5),0,dp(2));c.addView(t);if(!e.summary.isEmpty())c.addView(tx(e.summary,13,INK,false));if(!e.tags.isEmpty()){TextView z=tx("#"+String.join("  #",e.tags),11,ACCENT,false);z.setPadding(0,dp(6),0,0);c.addView(z);}TextView s=tx("出典："+e.sourceName,10,MUTED,false);s.setPadding(0,dp(7),0,0);c.addView(s);if(e.sourceUrl.startsWith("http")){Button o=nb("出典",v->open(e.sourceUrl));LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(dp(80),dp(38));p.gravity=Gravity.END;p.setMargins(0,dp(5),0,0);c.addView(o,p);}return c;}
    View card(ArchiveEvent e){LinearLayout c=col();c.setPadding(dp(15),dp(14),dp(15),dp(14));c.setBackground(bg(Color.WHITE,18,LINE));LinearLayout.LayoutParams cp=new LinearLayout.LayoutParams(-1,-2);cp.setMargins(0,dp(9),0,0);c.setLayoutParams(cp);LinearLayout m=new LinearLayout(this);m.setGravity(Gravity.CENTER_VERTICAL);TextView pill=tx(e.type,11,ACCENT,true);pill.setPadding(dp(8),dp(4),dp(8),dp(4));pill.setBackground(bg(SOFT,20,SOFT));m.addView(pill);m.addView(tx("  "+e.date+(e.time.isEmpty()?"":"  "+e.time),12,MUTED,false));c.addView(m);TextView t=tx(e.title,17,INK,true);t.setPadding(0,dp(9),0,dp(3));c.addView(t);if(!e.summary.isEmpty())c.addView(tx(e.summary,14,INK,false));if(!e.tags.isEmpty()){TextView z=tx("#"+String.join("  #",e.tags),12,ACCENT,false);z.setPadding(0,dp(8),0,0);c.addView(z);}TextView s=tx("出典："+e.sourceName+"  ·  "+e.confidence,11,MUTED,false);s.setPadding(0,dp(9),0,0);c.addView(s);if(e.sourceUrl.startsWith("http")){Button o=nb("出典ページを開く",v->open(e.sourceUrl));LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-2,dp(42));p.gravity=Gravity.END;p.setMargins(0,dp(7),0,0);c.addView(o,p);}return c;}
    View empty(String s){TextView v=tx(s,13,MUTED,false);v.setPadding(dp(15),dp(15),dp(15),dp(15));v.setBackground(bg(Color.WHITE,18,LINE));LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.setMargins(0,dp(10),0,dp(8));v.setLayoutParams(p);return v;}
    void open(String u){try{Uri x=Uri.parse(u);if(!"https".equalsIgnoreCase(x.getScheme())&&!"http".equalsIgnoreCase(x.getScheme()))return;startActivity(new Intent(Intent.ACTION_VIEW,x));}catch(Exception ignored){Toast.makeText(this,"ページを開けませんでした",Toast.LENGTH_SHORT).show();}}
    LinearLayout col(){LinearLayout l=new LinearLayout(this);l.setOrientation(LinearLayout.VERTICAL);l.setBackgroundColor(PAPER);return l;} ScrollView scroll(View v){ScrollView s=new ScrollView(this);s.setFillViewport(true);s.addView(v,new ScrollView.LayoutParams(-1,-2));return s;} void screen(View v){content.removeAllViews();content.addView(v,new FrameLayout.LayoutParams(-1,-1));} TextView tx(String s,int z,int c,boolean b){TextView v=new TextView(this);v.setText(s);v.setTextSize(z);v.setTextColor(c);if(b)v.setTypeface(Typeface.DEFAULT,Typeface.BOLD);return v;} GradientDrawable bg(int f,int r,int st){GradientDrawable d=new GradientDrawable();d.setColor(f);d.setCornerRadius(dp(r));d.setStroke(dp(1),st);return d;} int dp(int v){return Math.round(v*getResources().getDisplayMetrics().density);}
}
