plugins {
    id 'com.android.application'
}

android {
    namespace 'com.example.radikotranscriber'
    compileSdk 35

    defaultConfig {
        applicationId "com.ponpains.radikotranscriber"
        minSdk 33
        targetSdk 35
        versionCode 9
        versionName "0.9"
    }

    signingConfigs {
        stableDebug {
            storeFile rootProject.file("debug.keystore")
            storePassword "android"
            keyAlias "androiddebugkey"
            keyPassword "android"
            storeType "JKS"
        }
    }

    buildTypes {
        debug {
            signingConfig signingConfigs.stableDebug
        }
        release {
            minifyEnabled false
        }
    }
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.7.0'
    implementation 'androidx.activity:activity:1.10.1'
    implementation 'androidx.core:core:1.15.0'
}
